# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioNote' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioNote
pod 'AFNetworking', '~> 3.0’  
pod 'Masonry', '~> 0.6.4'
pod 'MBProgressHUD', '~> 0.9.1'

end
